export const fields = {
  id: { sort_type: 'text', sortable: false, editable: false },
  tc: { sort_type: 'number', sortable: true, editable: false },
  status: {
    textAlign: 'center',
    sort_type: 'text',
    sortable: true,
    editable: true,
  },
  calc_type: { sort_type: 'text', sortable: true, editable: true },
  tags: { isTag: true, sortable: false, editable: true },
  ptags: { isTag: true, sortable: false, editable: true },
  bcd: { textAlign: 'right', sort_type: 'date', sortable: true, editable: true },
  doe: { textAlign: 'right', sort_type: 'date', sortable: true, editable: true },
  dot: { textAlign: 'right', sort_type: 'date', sortable: true, editable: true },
  dob: { textAlign: 'right', sort_type: 'date', sortable: true, editable: true },
  pbc: { sort_type: 'text', sortable: true, editable: true },
  hir_age: {
    textAlign: 'right',
    sort_type: 'number',
    sortable: true,
    editable: false,
  },
  calc_age: {
    textAlign: 'right',
    sort_type: 'number',
    sortable: true,
    editable: false,
  },
};
